# Generated by Django 4.2.10 on 2026-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
