# Generated by Django 4.2.10 on 2026-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_working_hours_to_company_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='brand_primary_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
