# Generated by Django 4.2.10 on 2026-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_allow_null_brand_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
