# Generated by Django 4.2.10 on 2026-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_working_hours_from_company_settings'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE companies "
                "SET storage_limit_gb = 99999 "
                "WHERE storage_limit_gb > 99999;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='company',
            name='storage_limit_gb',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=8, verbose_name='Storage limit (GB, e.g. 0.1 = 100 MB)'),
        ),
    ]
