# Generated by Django 4.2.10 on 2026-05-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_storage_limit_gb_to_decimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name_plural': 'Company Settings'},
        ),
    ]
