# Generated by Django 4.2.10 on 2026-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companysettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
