# Generated by Django 4.2.10 on 2026-06-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_categories_company_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_name',
        ),
    ]
