# Generated by Django 4.2.10 on 2026-06-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_remove_contact_name_from_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
    ]
