# Generated by Django 4.2.10 on 2026-06-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_mappoint_width_height'),
        ('companies', '0012_remove_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='floor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='services.floor'),
        ),
    ]
