# Generated by Django 4.2.10 on 2026-06-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_invitation_company_nullable'),
        ('companies', '0014_backfill_floor_fk_from_floor_string'),
    ]

    operations = [
    ]
