# Generated by Django 4.2.10

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Step 1/3: Add the status field with default='pending'.
    The old is_used BooleanField is kept in this step so that the data
    migration (0017) can read it to populate status correctly.
    """

    dependencies = [
        ('companies', '0015_merge_20260604_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted'),
                    ('expired', 'Expired'),
                    ('revoked', 'Revoked'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
    ]
