# Generated by Django 4.2.10 on 2026-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('building', 'Building-wide'), ('company', 'Company internal')], default='building', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('info', 'Information'), ('important', 'Important'), ('event', 'Event')], default='info', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=False, help_text='Send email to all recipients')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcement_reads',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
            ],
            options={
                'db_table': 'building_floors',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_type', models.CharField(choices=[('desk', 'Desk'), ('meeting_room', 'Meeting Room'), ('parking', 'Parking'), ('capsule', 'Capsule'), ('toilet', 'Toilet'), ('kitchen', 'Kitchen'), ('elevator', 'Elevator'), ('exit', 'Exit'), ('office', 'Office'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('x', models.FloatField(help_text='X coordinate on floor plan (0-100%)')),
                ('y', models.FloatField(help_text='Y coordinate on floor plan (0-100%)')),
            ],
            options={
                'db_table': 'building_map_points',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('supplies', 'Supplies'), ('general', 'General')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='new', max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_requests/')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_requests',
            },
        ),
    ]
