# Generated by Django 4.2.10 on 2026-04-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_storage_limit_gb_to_decimal'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='floor',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='floors/plans/'),
        ),
    ]
