# Generated by Django 4.2.10 on 2026-05-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clear_floor_values(apps, schema_editor):
    """Null out the legacy integer floor column before converting it to a FK."""
    ServiceRequest = apps.get_model('services', 'ServiceRequest')
    ServiceRequest.objects.update(floor=None)


def backfill_creator_and_company(apps, schema_editor):
    """Preserve legacy ownership fields when moving from user -> created_by/company."""
    ServiceRequest = apps.get_model('services', 'ServiceRequest')
    for request in ServiceRequest.objects.select_related('user').all():
        if request.created_by_id is None and request.user_id is not None:
            request.created_by_id = request.user_id
        if request.company_id is None and request.user_id is not None:
            request.company_id = getattr(request.user, 'company_id', None)
        request.save(update_fields=['created_by', 'company'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_alter_storage_limit_gb_to_decimal'),
        ('services', '0002_initial'),
    ]

    operations = [
        # Clear existing integer floor values to avoid FK violation when
        # converting the column from PositiveIntegerField → ForeignKey.
        migrations.RunPython(clear_floor_values, migrations.RunPython.noop),
        migrations.AddField(
            model_name='servicerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='companies.company'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.floor'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='low', max_length=10),
        ),
        migrations.RunPython(backfill_creator_and_company, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
    ]
