# Generated by Django 4.2.10 on 2026-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_20260501_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='height',
            field=models.FloatField(blank=True, help_text='Height of the map point rectangle as % of floor plan (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='width',
            field=models.FloatField(blank=True, help_text='Width of the map point rectangle as % of floor plan (0-100)', null=True),
        ),
    ]
