# Generated by Django 4.2.10 on 2026-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_label_per_company'),
        ),
    ]
