# Generated by Django 4.2.10 on 2026-04-27 04:44

import apps.crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
        ('crm', '0003_label_unique_per_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='storage_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to='storage.file'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.crm.models._task_attachment_upload_path),
        ),
    ]
