# Generated by Django 4.2.10 on 2026-05-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_mime_type_storage_file_to_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task History', 'verbose_name_plural': 'Task Histories'},
        ),
    ]
