# Generated by Django 4.2.10 on 2026-05-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_taskhistory_add_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task History', 'verbose_name_plural': 'Task Histories'},
        ),
    ]
