# Generated by Django 4.2.10 on 2026-05-30 20:18

import apps.storage.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_taskhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.storage.upload_paths.task_attachment_upload_to),
        ),
    ]
