# Generated by Django 4.2.10 on 2026-04-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2026),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='leave_balances',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'year')},
        ),
    ]
