# Generated by Django 4.2.10 on 2026-04-29 04:58

import apps.hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leavebalance_year_and_unique_per_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=apps.hr.models.current_year),
        ),
    ]
