# Generated by Django 4.2.10 on 2026-05-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_leavebalance_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useronboardingprogress',
            options={'verbose_name': 'User Onboarding Progress', 'verbose_name_plural': 'User Onboarding Progresses'},
        ),
    ]
