# Generated by Django 4.2.10 on 2026-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_backfill_system_step_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtemplate',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
