# Common
SERVER_ERROR = 'SERVER_ERROR'
NOT_FOUND = 'NOT_FOUND'
PERMISSION_DENIED = 'PERMISSION_DENIED'
UNAUTHENTICATED = 'UNAUTHENTICATED'
VALIDATION_ERROR = 'VALIDATION_ERROR'

# Auth
EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
TOKEN_INVALID = 'TOKEN_INVALID'
TOKEN_EXPIRED = 'TOKEN_EXPIRED'
TOKEN_ALREADY_USED = 'TOKEN_ALREADY_USED'
SESSION_IDLE_TIMEOUT = 'SESSION_IDLE_TIMEOUT'
SESSION_ABSOLUTE_TIMEOUT = 'SESSION_ABSOLUTE_TIMEOUT'

# Booking
BOOKING_ADVANCE_DAYS_EXCEEDED = 'BOOKING_ADVANCE_DAYS_EXCEEDED'
BOOKING_CONFLICT = 'BOOKING_CONFLICT'
BOOKING_RESOURCE_INACTIVE = 'BOOKING_RESOURCE_INACTIVE'
BOOKING_CANCEL_WINDOW_PASSED = 'BOOKING_CANCEL_WINDOW_PASSED'
BOOKING_DURATION_TOO_SHORT = 'BOOKING_DURATION_TOO_SHORT'
BOOKING_DURATION_TOO_LONG = 'BOOKING_DURATION_TOO_LONG'
BOOKING_PARKING_WHOLE_DAY_ONLY = 'BOOKING_PARKING_WHOLE_DAY_ONLY'
BOOKING_DESK_USER_OVERLAP = 'BOOKING_DESK_USER_OVERLAP'

# CRM
CRM_WIP_LIMIT_EXCEEDED = 'CRM_WIP_LIMIT_EXCEEDED'
CRM_TASK_NOT_FOUND = 'CRM_TASK_NOT_FOUND'
CRM_COLUMN_NOT_FOUND = 'CRM_COLUMN_NOT_FOUND'
CRM_BOARD_NOT_FOUND = 'CRM_BOARD_NOT_FOUND'

# Storage
STORAGE_LIMIT_EXCEEDED = 'STORAGE_LIMIT_EXCEEDED'
STORAGE_FILE_TOO_LARGE = 'STORAGE_FILE_TOO_LARGE'
STORAGE_FOLDER_NOT_FOUND = 'STORAGE_FOLDER_NOT_FOUND'

# Company
COMPANY_INVITE_INVALID = 'COMPANY_INVITE_INVALID'
COMPANY_INVITE_EXPIRED = 'COMPANY_INVITE_EXPIRED'
COMPANY_INVITE_ALREADY_USED = 'COMPANY_INVITE_ALREADY_USED'
COMPANY_MEMBER_LIMIT_EXCEEDED = 'COMPANY_MEMBER_LIMIT_EXCEEDED'
COMPANY_CANNOT_REMOVE_SELF = 'COMPANY_CANNOT_REMOVE_SELF'
COMPANY_CANNOT_REMOVE_ADMIN = 'COMPANY_CANNOT_REMOVE_ADMIN'
COMPANY_CANNOT_DEACTIVATE_SELF = 'COMPANY_CANNOT_DEACTIVATE_SELF'
COMPANY_REASSIGN_TO_INVALID = 'COMPANY_REASSIGN_TO_INVALID'
COMPANY_REASSIGN_TO_NOT_ACTIVE = 'COMPANY_REASSIGN_TO_NOT_ACTIVE'

# Access
ACCESS_PASS_EXPIRED = 'ACCESS_PASS_EXPIRED'
ACCESS_PASS_REVOKED = 'ACCESS_PASS_REVOKED'

# HR
HR_LEAVE_OVERLAP = 'HR_LEAVE_OVERLAP'
HR_LEAVE_NOT_FOUND = 'HR_LEAVE_NOT_FOUND'
