# Generated by Django 4.2.10 on 2026-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('cancel_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_participants',
            },
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveIntegerField(help_text='0=Mon .. 6=Sun')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurring_bookings',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('desk', 'Desk'), ('meeting_room', 'Meeting Room'), ('parking', 'Parking'), ('capsule', 'Capsule')], db_index=True, max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conf', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_dock', models.BooleanField(default=False)),
                ('has_power_outlet', models.BooleanField(default=True)),
                ('min_duration_minutes', models.PositiveIntegerField(default=30)),
                ('max_duration_minutes', models.PositiveIntegerField(default=480)),
                ('advance_booking_days', models.PositiveIntegerField(default=14)),
                ('min_cancel_minutes', models.PositiveIntegerField(default=30)),
                ('available_days', models.JSONField(default=list, help_text='[0,1,2,3,4] Mon=0..Sun=6')),
                ('available_from', models.TimeField(default='08:00')),
                ('available_until', models.TimeField(default='22:00')),
                ('is_hot_desk', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('capsule_zone', models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('regular', 'Regular')], default='', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'resource_blocks',
            },
        ),
    ]
