# Generated by Django 4.2.10 on 2026-04-15 10:13
# Column already exists in the database (was created by a migration that was
# later removed). This migration only updates Django's state to match the DB.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # column already exists in DB — skip DDL
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='reminder_sent',
                    field=models.BooleanField(db_index=True, default=False),
                ),
            ],
        ),
    ]
