# Generated by Django 4.2.10 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingcancellationaudit',
            new_name='booking_can_booking_ce2476_idx',
            old_name='booking_can_booking_2bc640_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingcancellationaudit',
            new_name='booking_can_cancell_c77540_idx',
            old_name='booking_can_cancell_5bcf22_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
