# Generated by Django 4.2.10 on 2026-04-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_merge_0006_booking_branches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingchangeaudit',
            new_name='booking_cha_booking_c4b201_idx',
            old_name='booking_cha_booking_76d5df_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingchangeaudit',
            new_name='booking_cha_changed_21afbf_idx',
            old_name='booking_cha_changed_903f85_idx',
        ),
    ]
