# Generated by Django 4.2.10 on 2026-05-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_rename_booking_cha_booking_76d5df_idx_booking_cha_booking_c4b201_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='resources/photos/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.resource')),
            ],
            options={
                'db_table': 'resource_photos',
                'ordering': ['created_at'],
            },
        ),
    ]
