# Generated by Django 4.2.10 on 2026-05-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_mappoint_width_height'),
        ('bookings', '0009_resourcephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='floor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='services.floor'),
        ),
    ]
