# Generated by Django 4.2.10 on 2026-05-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_invitation_company_nullable'),
        ('bookings', '0009_resourcephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbooking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bookings', to='companies.company'),
        ),
    ]
