# Generated by Django 4.2.10 on 2026-05-30 19:50

from django.db import migrations


def populate_floor_fk(apps, schema_editor):
    Resource = apps.get_model('bookings', 'Resource')
    Floor = apps.get_model('services', 'Floor')
    for resource in Resource.objects.all():
        if resource.floor:
            floor = Floor.objects.filter(number=resource.floor).first()
            if floor:
                resource.floor_fk = floor
                resource.save(update_fields=['floor_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_resource_floor_fk'),
    ]

    operations = [
        migrations.RunPython(populate_floor_fk, migrations.RunPython.noop),
    ]
