# Generated by Django 4.2.10 on 2026-06-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_recurringbooking_company'),
        ('bookings', '0011_populate_resource_floor_fk'),
    ]

    operations = [
    ]
