# Generated by Django 4.2.10 on 2026-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_merge_20260604_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Booking priority tier: 1=basic/guest, 2=standard, 3=premium/superadmin'),
        ),
    ]
