# Generated by Django 4.2.10 on 2026-06-11

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_merge_20260604_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(
                blank=True,
                default='',
                upload_to=apps.bookings.models._booking_qr_upload_path,
            ),
        ),
    ]
