# Generated by Django 4.2.10 on 2026-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_merge_0013_booking_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringbooking',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], db_index=True, default='weekly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringbooking',
            name='day_of_week',
            field=models.PositiveIntegerField(blank=True, help_text='0=Mon .. 6=Sun (weekly only)', null=True),
        ),
    ]
