# Generated by Django 4.2.10 on 2026-04-02 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_point', models.CharField(blank=True, default='', max_length=100)),
                ('method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_entry', models.BooleanField(default=True, help_text='True=entry, False=exit')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('visit_purpose', models.TextField(blank=True, default='')),
                ('qr_code', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10)),
                ('usage_type', models.CharField(choices=[('single', 'Single use'), ('multi', 'Multi use')], default='single', max_length=10)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_passes',
            },
        ),
    ]
