# Generated by Django 4.2.10 on 2026-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='guestpass',
                    name='qr_image',
                    field=models.ImageField(blank=True, null=True, upload_to='guest_passes/qr/'),
                ),
            ],
        ),
    ]
