# Generated by Django 4.2.10 on 2026-04-28 13:13

import apps.access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='qr_image',
            field=models.ImageField(blank=True, default='', upload_to=apps.access.models._guest_pass_qr_upload_path),
        ),
    ]
