from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0004_guestpass_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='resend_attempts_in_window',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='resend_window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
# Generated by Django 4.2.10 on 2026-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_guestpass_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='resend_attempts_in_window',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='resend_window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
