# Generated by Django 4.2.10 on 2026-05-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_guestpass_resend_rate_limit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestpass',
            options={'verbose_name': 'Guest Pass', 'verbose_name_plural': 'Guest passes'},
        ),
    ]
