# Generated by Django 4.2.10 on 2026-06-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_qr_fields'),
        ('access', '0006_alter_guestpass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='access_logs',
                to='bookings.booking',
            ),
        ),
    ]
