# Generated by Django 4.2.10 on 2026-05-30 20:18

import apps.storage.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.storage.upload_paths.company_storage_file_upload_to),
        ),
    ]
