# Generated by Django 4.2.10 on 2026-06-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_add_comment_to_fileshare'),
        ('storage', '0003_alter_file_file'),
    ]

    operations = [
    ]
