# Generated by Django 4.2.10 on 2026-06-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0004_merge_20260604_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('permission', models.CharField(choices=[('view', 'View only'), ('upload', 'View + Upload'), ('full', 'Full access')], default='view', max_length=10)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='storage.folder')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_folder_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_folder_permissions',
                'indexes': [models.Index(fields=['folder', 'user'], name='storage_fol_folder__c3e142_idx'), models.Index(fields=['folder', 'role'], name='storage_fol_folder__749aac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role__isnull', True), ('user__isnull', False)), models.Q(('role__isnull', False), ('user__isnull', True)), _connector='OR'), name='folder_permission_user_xor_role'),
        ),
    ]
