# Generated by Django 4.2.10 on 2026-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_folderpermission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('folder', 'user'), name='unique_folder_user_perm'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('folder', 'role'), name='unique_folder_role_perm'),
        ),
    ]
