# Generated by Django 4.2.10 on 2026-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('task_assigned', 'Task Assigned'), ('task_moved', 'Task Moved'), ('task_comment', 'Task Comment'), ('task_deadline_soon', 'Task Deadline Soon'), ('task_deadline_overdue', 'Task Deadline Overdue'), ('guest_arrived', 'Guest Arrived'), ('pass_expiring', 'Pass Expiring'), ('service_accepted', 'Service Request Accepted'), ('service_status', 'Service Request Status'), ('service_completed', 'Service Request Completed'), ('announcement_building', 'Building Announcement'), ('announcement_company', 'Company Announcement'), ('invite_received', 'Invitation Received'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('new_employee', 'New Employee Joined')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', help_text='Frontend path to navigate', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_in_app', models.BooleanField(default=True)),
                ('booking_email', models.BooleanField(default=True)),
                ('task_in_app', models.BooleanField(default=True)),
                ('task_email', models.BooleanField(default=False)),
                ('access_in_app', models.BooleanField(default=True)),
                ('access_email', models.BooleanField(default=True)),
                ('service_in_app', models.BooleanField(default=True)),
                ('service_email', models.BooleanField(default=False)),
                ('announcement_in_app', models.BooleanField(default=True)),
                ('announcement_email', models.BooleanField(default=False)),
                ('hr_in_app', models.BooleanField(default=True)),
                ('hr_email', models.BooleanField(default=True)),
                ('do_not_disturb', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
