# Generated by Django 4.2.10 on 2026-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('task_assigned', 'Task Assigned'), ('task_moved', 'Task Moved'), ('task_comment', 'Task Comment'), ('task_deadline', 'Task Deadline'), ('task_deadline_soon', 'Task Deadline Soon'), ('task_deadline_overdue', 'Task Deadline Overdue'), ('guest_validated', 'Guest Validated'), ('guest_arrived', 'Guest Arrived'), ('guest_pass_expiring', 'Guest Pass Expiring'), ('pass_expiring', 'Pass Expiring'), ('service_request_update', 'Service Request Update'), ('service_accepted', 'Service Request Accepted'), ('service_status', 'Service Request Status'), ('service_completed', 'Service Request Completed'), ('announcement', 'Announcement'), ('announcement_building', 'Building Announcement'), ('announcement_company', 'Company Announcement'), ('invitation', 'Invitation'), ('invite_received', 'Invitation Received'), ('leave_review', 'Leave Review'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('new_employee', 'New Employee Joined'), ('system', 'System')], db_index=True, max_length=30),
        ),
    ]
