# Generated by Django 4.2.10 on 2026-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_per_type_preference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_assigned_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_comment_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_deadline_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_moved_email',
            field=models.BooleanField(default=True),
        ),
    ]
