# Generated by Django 4.2.10 on 2026-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_backfill_task_email_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_assigned_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_comment_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_deadline_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='task_moved_email',
            field=models.BooleanField(default=False),
        ),
    ]
