# Generated by Django 4.2.10 on 2026-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_backfill_transactional_email_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='new_employee_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='new_employee_in_app',
            field=models.BooleanField(default=True),
        ),
    ]
